brand:
  name: Niklas Mikkelsen
menu-string: Menu

nav:
  - title: Involvement
    url: '#portfolio'
  - title: My Journey
    url: '#about'
  - title: Contact
    url: '#contact'

copyright: Copyright Niklas Mikkelsen 2018

social-buttons:
  - icon: fa fa-twitter
    url: 'https://twitter.com/NikMikk' 
  - icon: fa fa-facebook
    url: 'https://www.facebook.com/niklas.mikkelsen.1'
  - icon: fa fa-linkedin
    url: 'https://www.linkedin.com/in/mikkn/'

quicklinks:
  - title: Privacy Policy
    url: '#'
  - title: Terms of Use
    url: '#'

modal:
  date-string: ''
  client-string: ''
  category-string: ''
  close-icon: 'fa fa-times'
  close-string: 'Close Project'
